[package]
name = "rpe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.3"
gl33 = "0.2.1"
ultraviolet = "0.9.0"
glfw = "0.45.0"
imagine = "0.2.0"

[dev-dependencies]
